### ISSUE TITLE
run_error

### ISSUE THREAD

**Issue by QiuJianL** [yongzhuo/nlg-yongzhuo#1]
No such file or directory: 'cut_zhwiki_wiki_parse.txt',
您好，首先谢谢您的分享，上次报错缺少的数据集cut_zhwiki_wiki_parse.txt能提供下载链接么？再次感谢

**Comment by yongzhuo** [comment]
地址: [https://pan.baidu.com/s/1I3vydhmFEQ9nuPG2fDou8Q](https://pan.baidu.com/s/1I3vydhmFEQ9nuPG2fDou8Q) 提取码: rket

**Comment by QiuJianL** [comment]
谢谢
