### ISSUE TITLE
使用pip安装过程中出现下列错误，请问如何解决？

### ISSUE THREAD

**Issue by HeroSong666** [yongzhuo/nlg-yongzhuo#13]
error: subprocess-exited-with-error
  
  python setup.py egg_info did not run successfully.
  exit code: 1
  
  [15 lines of output]
  C:\Users\hs6\AppData\Local\Temp\pip-install-mw7z_iai\pandas_fd94fc07bd02449c82bdc4a3c67de894\setup.py:12: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
    import pkg_resources
  C:\Users\hs6\anaconda3\Lib\site-packages\setuptools\__init__.py:84: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.
  !!
  
          ********************************************************************************
          Requirements should be satisfied by a PEP 517 installer.
          If you are using pip, you can try `pip install --use-pep517`.
          ********************************************************************************
  
  !!
    dist.fetch_build_eggs(dist.setup_requires)
  error in pandas setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; Expected end or semicolon (after version specifier)
      pytz >= 2011k
           ~~~~~~~^
  [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

Encountered error while generating package metadata.

See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by yongzhuo** [comment]
请问你的系统、python环境是什么

**Comment by HeroSong666** [comment]
> 请问你的系统、python环境是什么

windows系统，python 3.11, 直接在jupyter上面运行的

**Comment by yongzhuo** [comment]
3.11可能不支持，只测过3.6, 3.7, 3.8
