### ISSUE TITLE
数据问题

### ISSUE THREAD

**Issue by saxh** [yongzhuo/nlg-yongzhuo#3]
你好，你的摘要数据用的是百度云里哪一个数据啊？

**Comment by yongzhuo** [comment]
# nlg_yongzhuo/data
  * 哈工大的新浪微博短文本摘要[LCSTS](http://icrc.hitsz.edu.cn/Article/show/139.html)
  * 教育新闻自动摘要语料[chinese_abstractive_corpus](https://github.com/wonderfulsuccess/chinese_abstractive_corpus)
  * NLPCC 2017 task3[Single Document Summarization](http://tcci.ccf.org.cn/conference/2017/taskdata.php)
  * 娱乐新闻等[“神策杯”2018高校算法大师赛 ](https://www.dcjingsai.com/common/cmpt/%E2%80%9C%E7%A5%9E%E7%AD%96%E6%9D%AF%E2%80%9D2018%E9%AB%98%E6%A0%A1%E7%AE%97%E6%B3%95%E5%A4%A7%E5%B8%88%E8%B5%9B_%E7%AB%9E%E8%B5%9B%E4%BF%A1%E6%81%AF.html)

# other
[nlp_paper_notes/Summarization.md](https://github.com/bifeng/nlp_paper_notes/blob/75cf64a7eb244814fccf241d5990e23526352ab3/Summarization.md)

**Comment by 520jefferson** [comment]
CLES打算加入吗？http://icrc.hitsz.edu.cn/info/1037/1411.htm
