### ISSUE TITLE
意见反馈

### ISSUE THREAD

**Issue by ldj603** [yongzhuo/nlg-yongzhuo#4]
能够提供一个完整的东西，给一篇文章，直接输出摘要。

**Comment by yongzhuo** [comment]
你的意思是只返回指定个摘要句，不要score和排列所有的句子？

**Comment by ldj603** [comment]
除了score和排列所有的句子，再提供一个推荐的摘要。把topic进行组合，提炼出摘要。只是其中一个topic作为摘要的话，感觉信息丢失得太多。

**Comment by yongzhuo** [comment]
已整合更新，详见text_summarize。topic问题的话，选择topic_base中算法默认不是只取一个主题的的。
