### ISSUE TITLE
feature_base/text_teaser.py的问题

### ISSUE THREAD

**Issue by 1397981186** [yongzhuo/nlg-yongzhuo#5]
计算title为什么使用
(len_mix_word + 1.0) / (len_mix_word + 2.0) / len_title_word
论文原文里应该是
len_mix_word/len_title_word

**Comment by yongzhuo** [comment]
防止len_mix_word为零，即没有重合的word

**Comment by yongzhuo** [comment]
提高这个feature的权重（没有重合词语的时候）
